alpha: 2.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: ./models/td3_bc
device: cuda
discount: 0.99
env: hopper-medium-v2
eval_freq: 5000
expl_noise: 0.1
group: TD3_BC-D4RL
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: TD3_BC_hopper-medium-v2
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: CORL
seed: 0
tau: 0.005
