batch_size: 256
beta: 10.0
buffer_size: 10000000
checkpoints_path: ./models/iql
device: cuda
discount: 0.99
env: antmaze-medium-play-v0
eval_freq: 5000
group: IQL-D4RL
iql_deterministic: false
iql_tau: 0.9
load_model: ''
max_timesteps: 1000000
n_episodes: 100
name: IQL_antmaze-medium-play-v0
normalize: true
normalize_reward: true
project: CORL
seed: 0
tau: 0.005
