repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.255'
    hooks:
      - id: ruff
        args: [--show-source, --fix, --exit-non-zero-on-fix]
#        args: [--show-source]