batch_size: 256
beta: 3.0
buffer_size: 10000000
checkpoints_path: ./models/iql
device: cuda
discount: 0.99
env: maze2d-umaze-v1
eval_freq: 5000
group: IQL-D4RL
iql_deterministic: false
iql_tau: 0.7
load_model: ''
max_timesteps: 1000000
n_episodes: 100
name: IQL_maze2d-umaze-v1
normalize: true
normalize_reward: false
project: CORL
seed: 0
tau: 0.005

