env: antmaze-medium-play-v2
group: cql-antmaze-medium-play-v2-multiseed-v0
name: CQL
project: CORL
cql_min_q_weight: 5.0
cql_max_target_backup: true
cql_target_action_gap: 0.2
orthogonal_init: true
cql_lagrange: true
cql_temp: 1.0
policy_lr: 0.0001
qf_lr: 0.0003
cql_clip_diff_min: -200
normalize_reward: true
reward_scale: 100
reward_bias: -5.0
bc_steps: 40000
max_timesteps: 1200000
policy_log_std_multiplier: 0.0

alpha_multiplier: 1.0
backup_entropy: false
batch_size: 256
buffer_size: 10000000
checkpoints_path: null
cql_clip_diff_max: .inf
cql_importance_sample: true
<<<<<<< HEAD:configs/offline/cql/pen/cloned_v1.yaml
cql_lagrange: false
cql_max_target_backup: false
cql_min_q_weight: 1.0
=======
>>>>>>> main:configs/offline/cql/antmaze/medium_play_v2.yaml
cql_n_actions: 10
device: cuda
discount: 0.99
<<<<<<< HEAD:configs/offline/cql/pen/cloned_v1.yaml
env: pen-cloned-v1
eval_freq: 5000
group: cql-pen-cloned-v1-multiseed-v0
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: CQL
normalize: true
normalize_reward: false
orthogonal_init: true
policy_lr: 1.0e-04
project: CORL
qf_lr: 0.0003
=======
eval_freq: 5000
load_model: ''
n_episodes: 100
soft_target_update_rate: 0.005
normalize: true
>>>>>>> main:configs/offline/cql/antmaze/medium_play_v2.yaml
seed: 0
target_update_period: 1
q_n_hidden_layers: 3
reward_scale: 1.0
reward_bias: 0.0
use_automatic_entropy_tuning: true
