batch_size: 256
buffer_size: 10000000
checkpoints_path: ./models/bc_10
device: cuda
discount: 0.99
env: maze2d-medium-dense-v1
eval_freq: 5000
frac: 0.1
group: BC_10-D4RL
load_model: ''
max_timesteps: 1000000
max_traj_len: 1000
n_episodes: 100
name: BC_10_maze2d-medium-dense-v1
normalize: true
project: CORL
seed: 0
