batch_size: 256
buffer_size: 10000000
checkpoints_path: ./models/bc
device: cuda
discount: 0.99
env: walker2d-expert-v2
eval_freq: 5000
frac: 1.0
group: BC-D4RL
load_model: ''
max_timesteps: 1000000
max_traj_len: 1000
n_episodes: 10
name: BC_walker2d-expert-v2
normalize: true
project: CORL
seed: 0
